### ISSUE TITLE
Possible bug in handling VRML PROTO definition

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#113] opened 2022-06-28 15:40 UTC
When I define a PROTO with several nodes in the PROTO definition...

Only the first one is shown with X_ITE
All nodes are shown with BS Contact

I always assumed that the PROTO definition is a grouping node like BillBoard.
**But I am not sure about it.**

Example:

#VRML V2.0 utf8

PROTO Balls []
{
   Shape { appearance Appearance { material Material { diffuseColor 1 0 0 }} geometry Sphere {} }
  Transform { translation 2 0 0 children [ Shape { appearance Appearance { material Material { diffuseColor 0 1 0 }} geometry Sphere {} } ] }
}

Balls {}

With X_ITE I see only the Red Sphere
With BS_Contact I see both the Red and the Green Sphere

Of course, I can use a Group node to fix this. Just wondering what the actual definition is.
Is it a bug in X_ITE or a feature in BS_Contact?

X_ITE  5.0.3
Windows 10
Google Chrome

**Comment by create3000** [comment] 2022-06-28 15:54
This is not a bug, this is exactly how PROTOs should work. 

In https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/concepts.html#PROTOdefinitionsemantics is defined that: The first node type determines how instantiations of the prototype can be used in an X3D file. Only the first node in the body of a prototype is rendered, while peer nodes (which follow) are not displayed but remain active.

This makes sense because PROTOs can be assigned to SFNode fields like Shape.geometry.

If you wish a grouping node facility, just use a Group node as first root node of your PROTO.

**Comment by olafgithub** [comment] 2022-06-28 16:37
The linked specification makes it a lot cleared for me.
I tried to look it up but searched for VRML.
   
So it looks like BS Contact did it the Microsoft way: introduce a new feature to make your product incompatible...

Anyway, it is easy to use a Group node as I already figured out.

Thanks for clearing this up!

Olaf

**Closed** 2022-12-19 22:52 UTC
Labels: question

**Comment by splace** [comment] 2023-06-03 17:17
FYI i recall this 'feature' of blaxuun/bscontact. very unfortunate because...

valid worlds work fine, so the browser is conforming, but other things, like this, also work, resulting in a many worlds that only work in this browser. for some reason the spec. doesn't really stop this, i think it REALLY should have.
